// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ilhame90/gymshark-task/internal/models"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// NumberOfPacks mocks base method.
func (m *MockUsecase) NumberOfPacks(ctx context.Context, orderedItems int) []models.Pack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumberOfPacks", ctx, orderedItems)
	ret0, _ := ret[0].([]models.Pack)
	return ret0
}

// NumberOfPacks indicates an expected call of NumberOfPacks.
func (mr *MockUsecaseMockRecorder) NumberOfPacks(ctx, orderedItems interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberOfPacks", reflect.TypeOf((*MockUsecase)(nil).NumberOfPacks), ctx, orderedItems)
}
