// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package http

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NumberOfPacksRequest defines model for NumberOfPacksRequest.
type NumberOfPacksRequest struct {
	// OrderedItems Amount of the ordered items
	OrderedItems int `json:"ordered_items"`
}

// Pack defines model for Pack.
type Pack struct {
	Name     int `json:"name"`
	Quantity int `json:"quantity"`
}

// PostOrderJSONRequestBody defines body for PostOrder for application/json ContentType.
type PostOrderJSONRequestBody = NumberOfPacksRequest
